import React, { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronDown, CloudSun, Download, Eye, EyeOff, GripVertical, LayoutDashboard, Lock, Maximize2, Minus, NotebookPen, Pause, Play, Plus, Quote, RotateCcw, Settings2, TimerReset, Trash2, Type, Unlock, Upload, X } from "lucide-react";
import { Responsive, WidthProvider } from "react-grid-layout/legacy";

const Grid = WidthProvider(Responsive);
const ids = ["clock", "weather", "quote", "tasks", "pomodoro", "links", "habits", "notes"];
const defaultVisible = ids.slice(0, 6);
const info = {
  clock: ["Clock & date", "A live view of your day"], weather: ["Weather", "A quick local forecast"],
  quote: ["Daily quote", "A small thought for the day"], tasks: ["Task list", "Keep priorities nearby"],
  pomodoro: ["Pomodoro", "A focused work timer"], links: ["Quick links", "Your most used destinations"],
  habits: ["Habit tracker", "Build a little consistency"], notes: ["Scratchpad", "A place for passing thoughts"]
};
const initialLayouts = {
  lg: [{i:"clock",x:0,y:0,w:3,h:3,minW:2,minH:3},{i:"quote",x:3,y:0,w:5,h:3,minW:3,minH:3},{i:"tasks",x:8,y:0,w:4,h:8,minW:2,minH:4},{i:"pomodoro",x:0,y:3,w:5,h:8,minW:2,minH:4},{i:"weather",x:5,y:3,w:3,h:8,minW:2,minH:5},{i:"links",x:8,y:8,w:4,h:3,minW:3,minH:3},{i:"habits",x:0,y:11,w:6,h:4,minW:3,minH:4},{i:"notes",x:6,y:11,w:6,h:4,minW:3,minH:4}],
  md: [{i:"clock",x:0,y:0,w:3,h:3},{i:"quote",x:3,y:0,w:4,h:3},{i:"tasks",x:7,y:0,w:3,h:8},{i:"pomodoro",x:0,y:3,w:4,h:8},{i:"weather",x:4,y:3,w:3,h:8},{i:"links",x:7,y:8,w:3,h:3},{i:"habits",x:0,y:11,w:5,h:4},{i:"notes",x:5,y:11,w:5,h:4}],
  sm: [{i:"clock",x:0,y:0,w:6,h:3},{i:"quote",x:0,y:3,w:6,h:3},{i:"tasks",x:0,y:6,w:6,h:6},{i:"pomodoro",x:0,y:12,w:6,h:6},{i:"weather",x:0,y:18,w:6,h:5},{i:"links",x:0,y:23,w:6,h:4},{i:"habits",x:0,y:27,w:6,h:4},{i:"notes",x:0,y:31,w:6,h:4}]
};
const quotes = [["The best way to predict the future is to create it.","Peter Drucker"],["Small steps every day add up to big changes.","Unknown"],["You do not have to see the whole staircase, just take the first step.","Martin Luther King Jr."],["Do what you can, with what you have, where you are.","Theodore Roosevelt"],["Focus on being productive instead of busy.","Tim Ferriss"],["Simplicity is the ultimate sophistication.","Leonardo da Vinci"]];
const load = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } };
const normalizeLayouts = value => Object.fromEntries(Object.entries(value || initialLayouts).map(([breakpoint,items]) => [breakpoint,items.map(item => item.i === "weather" ? {...item,h:Math.max(item.h,breakpoint === "sm" ? 4 : 5),minH:breakpoint === "sm" ? 4 : 5} : item)]));
const weatherDescription = code => ({0:"Clear sky",1:"Mainly clear",2:"Partly cloudy",3:"Overcast",45:"Foggy",48:"Rime fog",51:"Light drizzle",53:"Drizzle",55:"Heavy drizzle",56:"Freezing drizzle",57:"Freezing drizzle",61:"Light rain",63:"Rain",65:"Heavy rain",66:"Freezing rain",67:"Freezing rain",71:"Light snow",73:"Snow",75:"Heavy snow",77:"Snow grains",80:"Rain showers",81:"Rain showers",82:"Heavy showers",85:"Snow showers",86:"Heavy snow showers",95:"Thunderstorm",96:"Thunderstorm with hail",99:"Thunderstorm with hail"}[code] || "Conditions unavailable");

function IconButton({ label, onClick, children, className = "" }) { return <button type="button" className={`icon-button ${className}`} title={label} aria-label={label} onClick={onClick}>{children}</button>; }
function Frame({ id, editing, remove, children }) { return <section className={`widget widget-${id}`}>{editing && <div className="widget-tools"><GripVertical size={18} className="drag-handle" title="Drag widget"/><IconButton label={`Remove ${info[id][0]}`} onClick={() => remove(id)}><X size={16}/></IconButton></div>}<div className="widget-content">{children}</div>{editing && <span className="resize-cue"><Maximize2 size={13}/></span>}</section>; }

export default function App() {
  const [editing, setEditing] = useState(false), [library, setLibrary] = useState(false), [settings, setSettings] = useState(false), [presets, setPresets] = useState(false), [backupMessage, setBackupMessage] = useState("");
  const [layouts, setLayouts] = useState(() => normalizeLayouts(load("dash-layouts", initialLayouts))), [visible, setVisible] = useState(() => load("dash-visible", defaultVisible));
  const [savedLayouts, setSavedLayouts] = useState(() => load("dash-saved-layouts", [])), [layoutName, setLayoutName] = useState("");
  const [tasks, setTasks] = useState(() => load("dash-tasks", []));
  const [taskText, setTaskText] = useState(""), [font, setFont] = useState(() => localStorage.getItem("dash-font") || "sans"), [theme, setTheme] = useState(() => localStorage.getItem("dash-theme") || "dusk"), [city, setCity] = useState(() => localStorage.getItem("dash-city") || "San Francisco");
  const [name, setName] = useState(() => localStorage.getItem("dash-name") || "Aiden"), [workspace, setWorkspace] = useState(() => localStorage.getItem("dash-workspace") || "My Dash"), [clockMode, setClockMode] = useState(() => localStorage.getItem("dash-clock") || "12"), [unit, setUnit] = useState(() => localStorage.getItem("dash-unit") || "F");
  const [appearance, setAppearance] = useState(() => ({accent:"#6658e8",opacity:88,blur:16,radius:14,spacing:18,wallpaper:"forest",imageUrl:"",brightness:85,imageBlur:0,...load("dash-appearance",{})}));
  const [topbarHidden, setTopbarHidden] = useState(() => localStorage.getItem("dash-topbar-hidden") === "true");
  const [links, setLinks] = useState(() => load("dash-links", [{ name:"GitHub", url:"https://github.com", color:"#5160c9" }, { name:"Docs", url:"https://docs.google.com", color:"#e06b48" }, { name:"Calendar", url:"https://calendar.google.com", color:"#e0a838" }, { name:"Music", url:"https://music.youtube.com", color:"#48a27e" }]));
  const [habits, setHabits] = useState(() => load("dash-habits", []));
  const [habitText, setHabitText] = useState("");
  const [note, setNote] = useState(() => localStorage.getItem("dash-note") || "");
  const [showSeconds, setShowSeconds] = useState(() => localStorage.getItem("dash-seconds") !== "false");
  const [now, setNow] = useState(new Date()), [quote, setQuote] = useState(0), [minutes, setMinutes] = useState(25), [left, setLeft] = useState(1500), [running, setRunning] = useState(false);
  const [weather, setWeather] = useState(null), [weatherStatus, setWeatherStatus] = useState("loading"), [weatherError, setWeatherError] = useState("");
  useEffect(() => { const interval = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(interval); }, []);
  useEffect(() => localStorage.setItem("dash-layouts", JSON.stringify(layouts)), [layouts]); useEffect(() => localStorage.setItem("dash-visible", JSON.stringify(visible)), [visible]); useEffect(() => localStorage.setItem("dash-saved-layouts", JSON.stringify(savedLayouts)), [savedLayouts]); useEffect(() => localStorage.setItem("dash-tasks", JSON.stringify(tasks)), [tasks]);
  useEffect(() => { document.documentElement.dataset.font = font; localStorage.setItem("dash-font", font); }, [font]); useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("dash-theme", theme); }, [theme]); useEffect(() => localStorage.setItem("dash-city", city), [city]);
  useEffect(() => localStorage.setItem("dash-name", name), [name]); useEffect(() => localStorage.setItem("dash-workspace", workspace), [workspace]); useEffect(() => localStorage.setItem("dash-clock", clockMode), [clockMode]); useEffect(() => localStorage.setItem("dash-unit", unit), [unit]); useEffect(() => localStorage.setItem("dash-appearance", JSON.stringify(appearance)), [appearance]); useEffect(() => localStorage.setItem("dash-links", JSON.stringify(links)), [links]); useEffect(() => localStorage.setItem("dash-topbar-hidden", String(topbarHidden)), [topbarHidden]); useEffect(() => localStorage.setItem("dash-habits", JSON.stringify(habits)), [habits]); useEffect(() => localStorage.setItem("dash-note", note), [note]); useEffect(() => localStorage.setItem("dash-seconds", String(showSeconds)), [showSeconds]);
  useEffect(() => { if (!running || !left) return; const interval = setInterval(() => setLeft(value => value - 1), 1000); return () => clearInterval(interval); }, [running, left]); useEffect(() => { if (!left) setRunning(false); }, [left]);
  useEffect(() => {
    if (!city.trim()) { setWeather(null); setWeatherStatus("error"); setWeatherError("Enter a city to see its weather."); return; }
    const controller = new AbortController();
    const timeout = window.setTimeout(async () => {
      setWeatherStatus("loading"); setWeatherError("");
      try {
        const query = new URLSearchParams({name:city.trim(),count:"1",language:"en",format:"json"});
        const locationResponse = await fetch(`https://geocoding-api.open-meteo.com/v1/search?${query}`, {signal:controller.signal});
        if (!locationResponse.ok) throw new Error("Location search is unavailable right now.");
        const locationData = await locationResponse.json();
        const place = locationData.results?.[0];
        if (!place) throw new Error("City not found. Check the spelling and try again.");
        const params = new URLSearchParams({latitude:place.latitude,longitude:place.longitude,current:"temperature_2m,relative_humidity_2m,weather_code",daily:"temperature_2m_max,temperature_2m_min",temperature_unit:unit === "F" ? "fahrenheit" : "celsius",timezone:"auto",forecast_days:"1"});
        const forecastResponse = await fetch(`https://api.open-meteo.com/v1/forecast?${params}`, {signal:controller.signal});
        if (!forecastResponse.ok) throw new Error("Weather service is unavailable right now.");
        const forecast = await forecastResponse.json();
        if (!forecast.current || !forecast.daily) throw new Error("No forecast is available for this location.");
        setWeather({name:place.name,region:[place.admin1,place.country].filter(Boolean).join(", "),temp:Math.round(forecast.current.temperature_2m),high:Math.round(forecast.daily.temperature_2m_max[0]),low:Math.round(forecast.daily.temperature_2m_min[0]),humidity:forecast.current.relative_humidity_2m,state:weatherDescription(forecast.current.weather_code)});
        setWeatherStatus("ready");
      } catch (error) {
        if (error.name === "AbortError") return;
        setWeather(null); setWeatherStatus("error"); setWeatherError(error.message || "Could not load weather.");
      }
    }, 450);
    return () => { window.clearTimeout(timeout); controller.abort(); };
  }, [city, unit]);
  const time = now.toLocaleTimeString([], {hour:"numeric", minute:"2-digit", hour12: clockMode === "12"}), sec = now.toLocaleTimeString([], {second:"2-digit"}), date = now.toLocaleDateString([], {weekday:"long",month:"short",day:"numeric"}), timer = `${String(Math.floor(left/60)).padStart(2,"0")}:${String(left%60).padStart(2,"0")}`;
  const setDuration = value => { setMinutes(value); setLeft(value * 60); setRunning(false); };
  const remove = id => setVisible(current => current.filter(item => item !== id));
  const addTask = event => { event.preventDefault(); if (!taskText.trim()) return; setTasks(current => [...current, {id:Date.now(),text:taskText.trim(),done:false}]); setTaskText(""); };
  const reset = () => { setLayouts(initialLayouts); setVisible(defaultVisible); };
  const resetAll = () => {
    if (!window.confirm("Reset all dashboard data? This clears tasks, notes, habits, saved layouts, and your settings.")) return;
    Object.keys(localStorage).filter(key => key.startsWith("dash-")).forEach(key => localStorage.removeItem(key));
    window.location.reload();
  };
  const addWidget = id => { setVisible(current => current.includes(id) ? current : [...current,id]); setLibrary(false); setEditing(true); };
  const updateLink = (index, field, value) => setLinks(current => current.map((link, item) => item === index ? { ...link, [field]: value } : link));
  const addHabit = event => { event.preventDefault(); if (!habitText.trim()) return; setHabits(current => [...current,{id:Date.now(),name:habitText.trim(),days:Array(7).fill(false)}]); setHabitText(""); };
  const toggleHabitDay = (habitId, dayIndex) => setHabits(current => current.map(habit => habit.id === habitId ? {...habit,days:habit.days.map((done,index) => index === dayIndex ? !done : done)} : habit));
  const jumpToSetting = title => document.querySelectorAll(".setting").forEach(section => { if (section.querySelector(":scope > span")?.textContent === title) section.scrollIntoView({behavior:"smooth",block:"start"}); });
  const applyPreset = preset => {
    const base = structuredClone(initialLayouts);
    if (preset === "minimal") {
      setVisible(["clock","weather","quote","links"]);
      base.lg = [{i:"clock",x:2,y:0,w:4,h:3},{i:"weather",x:2,y:3,w:4,h:5},{i:"quote",x:6,y:0,w:4,h:4},{i:"links",x:6,y:4,w:4,h:4}];
      base.md = [{i:"clock",x:1,y:0,w:4,h:3},{i:"weather",x:1,y:3,w:4,h:5},{i:"quote",x:5,y:0,w:4,h:4},{i:"links",x:5,y:4,w:4,h:4}];
      base.sm = [{i:"clock",x:0,y:0,w:6,h:3},{i:"weather",x:0,y:3,w:6,h:5},{i:"quote",x:0,y:8,w:6,h:3},{i:"links",x:0,y:11,w:6,h:5}];
    } else if (preset === "focus") {
      setVisible(["clock","weather","tasks","pomodoro","quote"]);
      base.lg = [{i:"clock",x:0,y:0,w:3,h:8},{i:"pomodoro",x:3,y:0,w:3,h:8},{i:"tasks",x:6,y:0,w:6,h:9},{i:"weather",x:0,y:8,w:6,h:6},{i:"quote",x:6,y:9,w:6,h:5}];
      base.md = [{i:"clock",x:0,y:0,w:3,h:8},{i:"pomodoro",x:3,y:0,w:3,h:8},{i:"tasks",x:6,y:0,w:4,h:9},{i:"weather",x:0,y:8,w:5,h:6},{i:"quote",x:5,y:9,w:5,h:5}];
      base.sm = [{i:"clock",x:0,y:0,w:6,h:3},{i:"pomodoro",x:0,y:3,w:6,h:4},{i:"tasks",x:0,y:7,w:6,h:6},{i:"quote",x:0,y:13,w:6,h:3},{i:"weather",x:0,y:16,w:6,h:4}];
    } else if (preset === "balanced") {
      setVisible(defaultVisible);
      base.lg = [{i:"clock",x:0,y:0,w:3,h:3},{i:"quote",x:3,y:0,w:5,h:3},{i:"tasks",x:8,y:0,w:4,h:8},{i:"pomodoro",x:0,y:3,w:5,h:8},{i:"weather",x:5,y:3,w:3,h:8},{i:"links",x:8,y:8,w:4,h:3}];
      base.md = [{i:"clock",x:0,y:0,w:3,h:3},{i:"quote",x:3,y:0,w:4,h:3},{i:"tasks",x:7,y:0,w:3,h:8},{i:"pomodoro",x:0,y:3,w:4,h:8},{i:"weather",x:4,y:3,w:3,h:8},{i:"links",x:7,y:8,w:3,h:3}];
      base.sm = [{i:"clock",x:0,y:0,w:6,h:3},{i:"quote",x:0,y:3,w:6,h:3},{i:"tasks",x:0,y:6,w:6,h:6},{i:"pomodoro",x:0,y:12,w:6,h:6},{i:"weather",x:0,y:18,w:6,h:5},{i:"links",x:0,y:23,w:6,h:4}];
    } else if (preset === "all") {
      setVisible(ids);
      base.lg = [{i:"clock",x:0,y:0,w:3,h:3},{i:"quote",x:3,y:0,w:5,h:3},{i:"weather",x:8,y:0,w:4,h:6},{i:"tasks",x:0,y:3,w:4,h:10},{i:"links",x:4,y:3,w:4,h:10},{i:"pomodoro",x:8,y:6,w:4,h:7},{i:"habits",x:0,y:13,w:6,h:5},{i:"notes",x:6,y:13,w:6,h:5}];
      base.md = [{i:"clock",x:0,y:0,w:3,h:3},{i:"quote",x:3,y:0,w:4,h:3},{i:"weather",x:7,y:0,w:3,h:6},{i:"tasks",x:0,y:3,w:3,h:10},{i:"links",x:3,y:3,w:4,h:10},{i:"pomodoro",x:7,y:6,w:3,h:7},{i:"habits",x:0,y:13,w:5,h:5},{i:"notes",x:5,y:13,w:5,h:5}];
      base.sm = [{i:"clock",x:0,y:0,w:6,h:3},{i:"quote",x:0,y:3,w:6,h:3},{i:"weather",x:0,y:6,w:6,h:5},{i:"tasks",x:0,y:11,w:6,h:7},{i:"links",x:0,y:18,w:6,h:7},{i:"pomodoro",x:0,y:25,w:6,h:6},{i:"habits",x:0,y:31,w:6,h:5},{i:"notes",x:0,y:36,w:6,h:5}];
    } else {
      setVisible(defaultVisible);
    }
    setLayouts(base); setPresets(false);
  };
  const saveCurrentLayout = event => {
    event.preventDefault();
    const title = layoutName.trim();
    if (!title) return;
    setSavedLayouts(current => [...current, {id:crypto.randomUUID(),name:title,layouts:structuredClone(layouts),visible:[...visible]}]);
    setLayoutName("");
  };
  const applySavedLayout = item => { setLayouts(normalizeLayouts(structuredClone(item.layouts))); setVisible([...item.visible]); setPresets(false); };
  const exportWorkspace = () => {
    const backup = { version:1, layouts, visible, tasks, habits, note, links, preferences:{font,theme,city,clockMode,unit,name,workspace,showSeconds,topbarHidden,appearance} };
    const url = URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = "my-dash-backup.json"; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url),1000); setBackupMessage("Backup downloaded.");
  };
  const importWorkspace = async event => {
    const file = event.target.files?.[0]; if (!file) return;
    try {
      const data = JSON.parse(await file.text());
      if (data.version !== 1 || !Array.isArray(data.visible) || !data.preferences) throw new Error("Unsupported backup format");
      if (data.layouts && typeof data.layouts === "object") setLayouts(data.layouts);
      setVisible(data.visible.filter(id => ids.includes(id)));
      if (Array.isArray(data.tasks)) setTasks(data.tasks);
      if (Array.isArray(data.habits)) setHabits(data.habits);
      if (typeof data.note === "string") setNote(data.note);
      if (Array.isArray(data.links)) setLinks(data.links);
      const p = data.preferences;
      if (p.font) setFont(p.font); if (p.theme) setTheme(p.theme); if (p.city) setCity(p.city); if (p.clockMode) setClockMode(p.clockMode); if (p.unit) setUnit(p.unit); if (p.name !== undefined) setName(p.name); if (p.workspace !== undefined) setWorkspace(p.workspace); if (p.showSeconds !== undefined) setShowSeconds(p.showSeconds); if (p.topbarHidden !== undefined) setTopbarHidden(p.topbarHidden); if (p.appearance) setAppearance(p.appearance);
      setBackupMessage("Backup restored.");
    } catch { setBackupMessage("That file is not a valid My Dash backup."); }
    event.target.value = "";
  };
  const morning = now.getHours() < 12 ? "morning" : now.getHours() < 18 ? "afternoon" : "evening";
  const wallpaperMap = {forest:"https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=2200&q=85",coast:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2200&q=85",night:"https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=2200&q=85",mountain:"https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=2200&q=85",city:"https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=2200&q=85"};
  const wallpaperUrl = appearance.wallpaper === "custom" && appearance.imageUrl ? appearance.imageUrl : wallpaperMap[appearance.wallpaper] || wallpaperMap.forest;
  const atmosphere = theme === "moss" ? "rgba(28,85,50,.54)" : theme === "sunset" ? "rgba(197,91,81,.47)" : "rgba(28,66,115,.36)";
  const appStyle = { "--accent": appearance.accent, "--card-opacity": appearance.opacity / 100, "--card-blur": `${appearance.blur}px`, "--card-radius": `${appearance.radius}px`, "--wallpaper": `url(${JSON.stringify(wallpaperUrl)})`, "--image-filter": `brightness(${appearance.brightness}%) blur(${appearance.imageBlur}px)`, "--atmosphere": `linear-gradient(135deg, ${atmosphere}, rgba(30,30,65,.1))` };
  return <main className={`app ${topbarHidden ? "header-hidden" : ""}`} style={appStyle}>
    {!topbarHidden ? <header className="topbar"><div className="brand"><span className="brand-mark"><LayoutDashboard size={22}/></span><div><strong>{workspace || "My Dash"}</strong><small>Customizable workspace</small></div></div><div className="actions"><button className="layout-button" type="button" onClick={() => setPresets(true)}><LayoutDashboard size={17}/><span>Layouts</span></button><button className={`layout-button ${editing ? "active" : ""}`} type="button" onClick={() => setEditing(value => !value)}>{editing ? <Unlock size={18}/> : <Lock size={18}/>}<span>{editing ? "Editing layout" : "Lock layout"}</span></button><button className="add-button" type="button" onClick={() => setLibrary(true)}><Plus size={19}/><span>Add widget</span></button><IconButton label="Open settings" onClick={() => setSettings(true)}><Settings2 size={21}/></IconButton><button className="layout-button hidebar-button" type="button" onClick={() => setTopbarHidden(true)}><EyeOff size={17}/><span>Hide bar</span></button></div></header> : <div className="compact-controls"><IconButton label="Show top bar" onClick={() => setTopbarHidden(false)}><Eye size={19}/></IconButton><IconButton label="Choose a layout" onClick={() => setPresets(true)}><LayoutDashboard size={19}/></IconButton><IconButton label="Add widget" onClick={() => setLibrary(true)}><Plus size={19}/></IconButton><IconButton label="Open settings" onClick={() => setSettings(true)}><Settings2 size={19}/></IconButton></div>}
    <section className="stage"><div className="welcome"><p>YOUR SPACE</p><h1>Good {morning}, {name || "there"}.</h1><span>{date}</span></div>
      <Grid className={`grid ${editing ? "editing" : ""}`} layouts={layouts} breakpoints={{lg:1100,md:760,sm:0}} cols={{lg:12,md:10,sm:6}} rowHeight={40} margin={[appearance.spacing,appearance.spacing]} containerPadding={[0,0]} compactType="vertical" isDraggable={editing} isResizable={editing} draggableHandle=".drag-handle" resizeHandles={["se"]} onLayoutChange={(_layout, all) => setLayouts(all)}>
        {visible.includes("clock") && <div key="clock"><Frame id="clock" editing={editing} remove={remove}><p className="label">Clock & date</p><div className="clock">{time}{showSeconds && <small>{sec}</small>}</div><p className="date">{date}</p></Frame></div>}
        {visible.includes("weather") && <div key="weather"><Frame id="weather" editing={editing} remove={remove}><p className="label">Weather</p><div className="weather-head"><div><h2>{weather?.name || city || "Weather"}</h2>{weather?.region && <small className="weather-region">{weather.region}</small>}<span>{weatherStatus === "loading" ? "Finding current conditions…" : weatherStatus === "error" ? "Weather unavailable" : weather.state}</span></div><CloudSun size={42}/></div>{weatherStatus === "ready" && weather ? <><div className="temp">{weather.temp}<sup>°</sup><small>{unit}</small></div><div className="weather-data"><span>High <b>{weather.high}°</b></span><span>Low <b>{weather.low}°</b></span><span>Humidity <b>{weather.humidity}%</b></span></div></> : <p className="weather-message" role="status">{weatherStatus === "loading" ? "Loading forecast…" : weatherError}</p>}</Frame></div>}
        {visible.includes("quote") && <div key="quote"><Frame id="quote" editing={editing} remove={remove}><p className="label">Daily quote</p><Quote className="quote-icon" size={29}/><blockquote>“{quotes[quote][0]}”</blockquote><div className="quote-bottom"><span>{quotes[quote][1]}</span><IconButton label="Show another quote" onClick={() => setQuote(value => (value + 1) % quotes.length)}><RotateCcw size={17}/></IconButton></div></Frame></div>}
        {visible.includes("tasks") && <div key="tasks"><Frame id="tasks" editing={editing} remove={remove}><p className="label">Task list</p><form className="task-form" onSubmit={addTask}><input aria-label="New task" value={taskText} onChange={event => setTaskText(event.target.value)} placeholder="Add a task..."/><button type="submit" aria-label="Add task"><Plus size={18}/></button></form><div className="tasks">{tasks.map(task => <div className={`task ${task.done ? "done" : ""}`} key={task.id}><button type="button" className="check" aria-label={`Mark ${task.text} complete`} onClick={() => setTasks(current => current.map(item => item.id === task.id ? {...item,done:!item.done} : item))}>{task.done && <Check size={14}/>}</button><span>{task.text}</span><IconButton className="delete" label={`Delete ${task.text}`} onClick={() => setTasks(current => current.filter(item => item.id !== task.id))}><Trash2 size={15}/></IconButton></div>)}</div><p className="task-count">{tasks.filter(task => task.done).length} of {tasks.length} completed</p></Frame></div>}
        {visible.includes("pomodoro") && <div key="pomodoro"><Frame id="pomodoro" editing={editing} remove={remove}><div className="timer-heading"><p className="label">Pomodoro timer</p><div className="preset"><button type="button" onClick={() => setDuration(Math.max(5,minutes-5))}><Minus size={14}/></button><span>{minutes} min</span><button type="button" onClick={() => setDuration(minutes+5)}><Plus size={14}/></button></div></div><div className="timer-face"><strong>{timer}</strong><small>{running ? "Focus in progress" : left === 0 ? "Complete" : "Ready when you are"}</small></div><div className="timer-controls"><button className="play" type="button" aria-label={running ? "Pause timer" : "Start timer"} onClick={() => setRunning(value => !value)}>{running ? <Pause size={20}/> : <Play size={20}/>}</button><IconButton label="Reset timer" onClick={() => { setRunning(false); setLeft(minutes * 60); }}><TimerReset size={19}/></IconButton></div></Frame></div>}
        {visible.includes("links") && <div key="links"><Frame id="links" editing={editing} remove={remove}><p className="label">Quick links</p><div className="links">{links.map((link, index) => <a key={`${link.name}-${index}`} href={link.url || "#dash"} target="_blank" rel="noreferrer"><i style={{background:link.color}}>{link.name.slice(0,2).toUpperCase()}</i>{link.name || "Link"}</a>)}</div><button className="shortcut" type="button" onClick={() => setSettings(true)}><Plus size={16}/>Customize shortcuts</button></Frame></div>}
        {visible.includes("habits") && <div key="habits"><Frame id="habits" editing={editing} remove={remove}><p className="label">Habit tracker</p><div className="habit-list">{habits.map(habit => <div className="habit" key={habit.id}><div className="habit-name">{habit.name}<span>{habit.days.filter(Boolean).length}/7</span></div><div className="habit-days">{["M","T","W","T","F","S","S"].map((day,index) => <button className={habit.days[index] ? "complete" : ""} type="button" key={index} aria-label={`${habit.name}, day ${index + 1}`} onClick={() => toggleHabitDay(habit.id,index)}>{habit.days[index] ? <Check size={12}/> : day}</button>)}</div><IconButton label={`Remove habit ${habit.name}`} className="remove-habit" onClick={() => setHabits(current => current.filter(item => item.id !== habit.id))}><X size={13}/></IconButton></div>)}</div><form className="habit-form" onSubmit={addHabit}><input aria-label="New habit" placeholder="Add a habit..." value={habitText} onChange={event => setHabitText(event.target.value)}/><button type="submit" aria-label="Add habit"><Plus size={16}/></button></form></Frame></div>}
        {visible.includes("notes") && <div key="notes"><Frame id="notes" editing={editing} remove={remove}><p className="label">Scratchpad</p><textarea className="scratchpad" aria-label="Scratchpad notes" placeholder="Jot down a thought..." value={note} onChange={event => setNote(event.target.value)}/></Frame></div>}
      </Grid>{editing && <p className="editing-note"><GripVertical size={16}/> Drag cards to rearrange. Pull the lower-right corner to resize.</p>}</section>
    {presets && <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) setPresets(false); }}><section className="preset-modal" role="dialog" aria-modal="true" aria-labelledby="preset-title"><div className="panel-head"><div><p>YOUR DASHBOARD</p><h2 id="preset-title">Layouts</h2></div><IconButton label="Close layouts" onClick={() => setPresets(false)}><X size={19}/></IconButton></div><h3 className="layout-section-title">Start with a preset</h3><div className="preset-options">{[["balanced","Balanced","Clock, quote, and tasks above timer, weather, and links."],["focus","Focus mode","Tall tasks at right; clock and timer above weather at left, with quote below."],["minimal","Minimal","A centered clock, weather, quote, and links."],["all","Everything","All eight widgets in a three-row workspace."]].map(([id,title,description]) => <button type="button" key={id} onClick={() => applyPreset(id)}><span className={`preset-preview ${id}`}><i/><i/><i/><i/></span><span><b>{title}</b><small>{description}</small></span></button>)}</div><h3 className="layout-section-title saved-title">Saved layouts</h3>{savedLayouts.length ? <div className="saved-layout-list">{savedLayouts.map(item => <div className="saved-layout" key={item.id}><button type="button" className="saved-layout-load" onClick={() => applySavedLayout(item)}><LayoutDashboard size={18}/><span>{item.name}<small>{item.visible.length} widgets</small></span></button><IconButton label={`Delete ${item.name}`} onClick={() => setSavedLayouts(current => current.filter(layout => layout.id !== item.id))}><Trash2 size={16}/></IconButton></div>)}</div> : <p className="empty-layouts">Save your current widget arrangement to reuse it here.</p>}<form className="save-layout-form" onSubmit={saveCurrentLayout}><input aria-label="Layout name" maxLength={32} placeholder="Name this layout" value={layoutName} onChange={event => setLayoutName(event.target.value)}/><button type="submit" disabled={!layoutName.trim()}><Plus size={16}/>Save current</button></form></section></div>}
    {library && <aside className="panel"><div className="panel-head"><div><p>WORKSPACE</p><h2>Add a widget</h2></div><IconButton label="Close widget library" onClick={() => setLibrary(false)}><X size={19}/></IconButton></div><div className="library">{ids.map(id => <button className="library-item" type="button" key={id} disabled={visible.includes(id)} onClick={() => addWidget(id)}><span>{id === "weather" ? <CloudSun size={19}/> : id === "quote" ? <Quote size={19}/> : id === "pomodoro" ? <TimerReset size={19}/> : id === "habits" ? <CalendarDays size={19}/> : id === "notes" ? <NotebookPen size={19}/> : <LayoutDashboard size={19}/>}</span><div><b>{info[id][0]}</b><small>{visible.includes(id) ? "Already on your board" : info[id][1]}</small></div><Plus size={18}/></button>)}</div></aside>}
    {settings && <aside className="panel"><div className="panel-head"><div><p>PREFERENCES</p><h2>Make it yours</h2></div><IconButton label="Close settings" onClick={() => setSettings(false)}><X size={19}/></IconButton></div><nav className="settings-nav" aria-label="Settings categories"><button type="button" onClick={() => jumpToSetting("Workspace identity")}>Workspace</button><button type="button" onClick={() => jumpToSetting("Wallpaper")}>Appearance</button><button type="button" onClick={() => jumpToSetting("Clock & weather")}>Widgets</button><button type="button" onClick={() => jumpToSetting("Backup & restore")}>Data</button></nav>
      <section className="setting" id="settings-workspace"><span>Workspace identity</span><label htmlFor="workspace-name">Workspace name</label><input id="workspace-name" value={workspace} onChange={event => setWorkspace(event.target.value)} /><label htmlFor="person-name">Your name</label><input id="person-name" value={name} onChange={event => setName(event.target.value)} /></section>
      <section className="setting"><span>Typeface</span>{[["sans","Modern sans"],["serif","Editorial serif"],["mono","Focus mono"],["rounded","Rounded"],["humanist","Humanist"]].map(([id,label]) => <button className={font === id ? "selected" : ""} type="button" key={id} onClick={() => setFont(id)}><Type size={17}/>{label}</button>)}</section>
      <section className="setting"><span>Wallpaper</span><div className="wallpapers">{[["forest","Forest"],["coast","Coast"],["night","Night"],["mountain","Yosemite"],["city","City"]].map(([id,label]) => <button className={appearance.wallpaper === id ? "selected" : ""} type="button" key={id} onClick={() => setAppearance(current => ({...current,wallpaper:id}))}><i className={`wallpaper-swatch ${id}`}/>{label}</button>)}</div><label htmlFor="wallpaper-url">Use your own image URL</label><div className="image-url"><input id="wallpaper-url" type="url" placeholder="https://example.com/image.jpg" value={appearance.imageUrl} onChange={event => setAppearance(current => ({...current,imageUrl:event.target.value,wallpaper:"custom"}))}/>{appearance.imageUrl && <IconButton label="Use custom wallpaper" onClick={() => setAppearance(current => ({...current,wallpaper:"custom"}))}><Check size={17}/></IconButton>}</div><small className="field-hint">Paste a direct link to a public image.</small><label>Image brightness <b>{appearance.brightness}%</b><input type="range" min="35" max="120" value={appearance.brightness} onChange={event => setAppearance(current => ({...current,brightness:Number(event.target.value)}))}/></label><label>Image softness <b>{appearance.imageBlur}px</b><input type="range" min="0" max="12" value={appearance.imageBlur} onChange={event => setAppearance(current => ({...current,imageBlur:Number(event.target.value)}))}/></label></section>
      <section className="setting"><span>Accent color</span><div className="accent-row">{["#6658e8","#e05d7a","#0b9c92","#e3883e","#3d78c5"].map(color => <button aria-label={`Use ${color} accent`} className={appearance.accent === color ? "accent selected" : "accent"} style={{background:color}} type="button" key={color} onClick={() => setAppearance(current => ({...current,accent:color}))}/>) }<label className="color-picker" title="Choose a custom accent"><input type="color" value={appearance.accent} onChange={event => setAppearance(current => ({...current,accent:event.target.value}))}/><Plus size={15}/></label></div></section>
      <section className="setting"><span>Card appearance</span><label>Transparency <b>{appearance.opacity}%</b><input type="range" min="55" max="100" value={appearance.opacity} onChange={event => setAppearance(current => ({...current,opacity:Number(event.target.value)}))}/></label><label>Glass blur <b>{appearance.blur}px</b><input type="range" min="0" max="28" value={appearance.blur} onChange={event => setAppearance(current => ({...current,blur:Number(event.target.value)}))}/></label><label>Corner roundness <b>{appearance.radius}px</b><input type="range" min="0" max="24" value={appearance.radius} onChange={event => setAppearance(current => ({...current,radius:Number(event.target.value)}))}/></label><label>Grid spacing <b>{appearance.spacing}px</b><input type="range" min="6" max="30" value={appearance.spacing} onChange={event => setAppearance(current => ({...current,spacing:Number(event.target.value)}))}/></label></section>
      <section className="setting"><span>Atmosphere</span>{[["dusk","Dusk"],["moss","Moss"],["sunset","Sunset"]].map(([id,label]) => <button className={`atmosphere-choice ${theme === id ? "selected" : ""}`} type="button" key={id} onClick={() => setTheme(id)}><i className={`swatch ${id}`}/>{label}</button>)}</section>
      <section className="setting"><span>Top bar</span><label className="toggle-row"><span>Hide header bar</span><input type="checkbox" checked={topbarHidden} onChange={event => setTopbarHidden(event.target.checked)}/><i/></label></section>
      <section className="setting"><span>Clock & weather</span><div className="choice-row"><button className={clockMode === "12" ? "selected" : ""} type="button" onClick={() => setClockMode("12")}>12-hour time</button><button className={clockMode === "24" ? "selected" : ""} type="button" onClick={() => setClockMode("24")}>24-hour time</button></div><label className="toggle-row"><span>Show seconds</span><input type="checkbox" checked={showSeconds} onChange={event => setShowSeconds(event.target.checked)}/><i/></label><div className="choice-row"><button className={unit === "F" ? "selected" : ""} type="button" onClick={() => setUnit("F")}>Fahrenheit</button><button className={unit === "C" ? "selected" : ""} type="button" onClick={() => setUnit("C")}>Celsius</button></div><label htmlFor="city">Weather location</label><div className="city"><input id="city" value={city} placeholder="City name" onChange={event => setCity(event.target.value)}/><ChevronDown size={17}/></div><small className="field-hint">Current conditions and today's high/low.</small></section>
      <section className="setting"><span>Shortcuts</span>{links.map((link,index) => <div className="link-editor" key={index}><input aria-label={`Shortcut ${index + 1} name`} value={link.name} onChange={event => updateLink(index,"name",event.target.value)} /><input aria-label={`Shortcut ${index + 1} URL`} value={link.url} onChange={event => updateLink(index,"url",event.target.value)} /><input aria-label={`Shortcut ${index + 1} color`} className="link-color" type="color" value={link.color} onChange={event => updateLink(index,"color",event.target.value)} /><IconButton label={`Remove ${link.name || "shortcut"}`} onClick={() => setLinks(current => current.filter((_,item) => item !== index))}><Trash2 size={15}/></IconButton></div>)}<button className="add-shortcut-setting" type="button" onClick={() => setLinks(current => [...current,{name:"New link",url:"https://",color:"#6658e8"}])}><Plus size={16}/>Add shortcut</button></section>
      <section className="setting backup-setting"><span>Backup & restore</span><button type="button" onClick={exportWorkspace}><Download size={16}/>Export dashboard</button><label className="import-button"><Upload size={16}/>Import dashboard<input type="file" accept="application/json,.json" onChange={importWorkspace}/></label>{backupMessage && <small className="field-hint" role="status">{backupMessage}</small>}<button className="reset-all" type="button" onClick={resetAll}><Trash2 size={16}/>Reset all data</button></section>
      <button className="reset" type="button" onClick={reset}><RotateCcw size={17}/>Reset widget layout</button></aside>}
    {(library || settings) && <button className="scrim" type="button" aria-label="Close panel" onClick={() => { setLibrary(false); setSettings(false); }}/>}</main>;
}
